version: '3.8'


services:
  backend_server:
    container_name: backend_server
    build: ./backend
    restart: always
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file: ".env"
    depends_on:
      - database


  database:
    image: postgres:latest
    container_name: database
    env_file: ".env"
    user: root
    ports:
      -  "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_SERVER}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRESQL_POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: ".env"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - database
  
  
  minio_server:
    image: minio/minio:latest
    container_name: minio_server
    command: server --console-address ":9001" /data/
    restart: always
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}